// This file is auto-generated by the Firebase Studio.
// Please do not edit this file manually, as your changes will be overwritten.
//
// For more information, please visit https://firebase.google.com/docs/studio
/* eslint-disable */
export const notosans =
  'AAEAAAARAQAABAAQRFNJTxL/AA/MAAAE4AAAAQdPUy8y2jD3SAAAQYQAAABgY21hcO6So04AAEG0AAAFHmdhc3AAAAAQAAFLuAAAAAhn... (very long base64 string) ...AAAAAAAAA==';
